name: Test ComfyUI Windows with Default Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  test-action:
    runs-on: win
    steps:
    - name: Use ComfyUI GitHub Action
      uses: comfy-org/comfy-action@main
      with:
        os: windows
        cuda_version: 12.1
        gcs_bucket_name: 'comfy-ci-results'
        workflow_filenames: "default.json,lora.json"
        google_credentials: ${{ secrets.GCS_SERVICE_ACCOUNT_JSON }}
        output_prefix: 'ComfyUI'
        timeout: 50