name: Test ComfyUI Example Workflows
on:
  workflow_dispatch:



jobs:
  test-default-workflow:
    strategy:
        fail-fast: false
        matrix:
          os: [macos]
          python_version: [3.8, 3.11]
          torch_version: [12.1]
          include:
            - os: macos
              runner_label: [self-hosted, dev-runner-yo]
            # - os: linux
            #   runner_label: [self-hosted, Linux, t4]
            # - os: win
            #   runner_label: [self-hosted, win]
    runs-on: ${{ matrix.runner_label }}
    steps:
    - name: Test Default Workflow
      uses: drip-art/comfy-action@yo-migrate-value-from-comfyui
      with:
        os: ${{ matrix.os }}
        cuda_version: ${{ matrix.cuda_version }}
        workflow_filenames: "default.json,lora.json"
        google_credentials: ${{ secrets.GCS_SERVICE_ACCOUNT_JSON }}
        comfyui_flags: 
        output_prefix: 'ComfyUI'
        timeout: 50