name: Test ComfyUI Example Workflows (Yoland)
on:
  workflow_dispatch:

jobs:
  test-default-workflow:
    strategy:
      fail-fast: false
      matrix:
        os: [macos, linux]
        python_version: [3.9]
        torch_version: [12.1]
        include:
          - os: macos
            runner_label: [self-hosted, macOS, m2]
          - os: linux
            runner_label: [self-hosted, Linux, t4]
          # - os: win
          #   python_version: 3.8
          #   torch_version: 12.1
          #   runner_label: self-hosted, win
    runs-on: ${{ matrix.runner_label }}
    steps:
      - name: Test Default Workflow
        uses: comfy-org/comfy-action@main
        with:
          os: ${{ matrix.os }}
          python_version: ${{ matrix.python_version }}
          torch_version: ${{ matrix.torch_version }}
          workflow_filenames: "default.json,lora.json"
          google_credentials: ${{ secrets.GCS_SERVICE_ACCOUNT_JSON }}
          comfyui_flags: ""
          output_prefix: 'ComfyUI'
          timeout: 50
